# Generated by Django 3.1 on 2020-09-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200904_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='checkbox_style',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
