# Generated by Django 3.1 on 2020-09-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200909_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
